
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#to change ports
#server:
#  port: 80
#  servlet:
#    context-path: /reimbursements

spring:
  datasource:
    username: root
    passsowrd:
    url: jdbc:mysql://34.70.141.197:3306/ReimbursementsDB

  jpa:
    hibernate:
     naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
