server:
  port: 7000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_APP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


